"""Fix schema consistency - update ticket and event models

Revision ID: f8d3428bab23
Revises: 2025_09_17_update_nft
Create Date: 2025-09-18 11:12:40.943748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f8d3428bab23'
down_revision: Union[str, Sequence[str], None] = '2025_09_17_update_nft'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('token_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_events_contract_address'), table_name='events')
    op.create_index(op.f('ix_events_token_id'), 'events', ['token_id'], unique=True)
    op.drop_column('events', 'contract_address')
    op.add_column('tickets', sa.Column('serial_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_tickets_contract_address'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_token_id'), table_name='tickets')
    op.create_index(op.f('ix_tickets_serial_number'), 'tickets', ['serial_number'], unique=False)
    op.drop_column('tickets', 'contract_address')
    op.drop_column('tickets', 'token_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('token_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('contract_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tickets_serial_number'), table_name='tickets')
    op.create_index(op.f('ix_tickets_token_id'), 'tickets', ['token_id'], unique=True)
    op.create_index(op.f('ix_tickets_contract_address'), 'tickets', ['contract_address'], unique=False)
    op.drop_column('tickets', 'serial_number')
    op.add_column('events', sa.Column('contract_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_events_token_id'), table_name='events')
    op.create_index(op.f('ix_events_contract_address'), 'events', ['contract_address'], unique=True)
    op.drop_column('events', 'token_id')
    # ### end Alembic commands ###
